### PR TITLE
Merge Draft1

### PR DESCRIPTION
**Pull request by haydenwoodhead**
Draft1 of delay-backend-apidocs adds initial endpoints along with parameters and responses. Example responses still need their example data fleshed out.

### CODE REVIEW

**Review by dominicbporter — CHANGES_REQUESTED** [review]
With endpoints and requiring ID's please show which ID's are required for what. EG line 101 should be/users/:user_id.
HTTP code of 418 needs to be added
Full examples JSON payloads of each endpoint

**Comment by haydenwoodhead** [comment]
Is it really necessary to specify what kind of id is needed? It's pretty self explanatory.

**Comment by Dharyin** [comment]
Clarity is never a bad thing.

On Sat, 19 Aug 2017 at 9:44 PM, Hayden Woodhead <notifications@github.com>
wrote:

> Is it really necessary to specify what kind of id is needed? It's pretty
> self explanatory.
>
> > On 19/08/2017, at 6:52 PM, dominicbporter <notifications@github.com>
> wrote:
> >
> > @dominicbporter requested changes on this pull request.
> >
> > With endpoints and requiring ID's please show which ID's are required
> for what. EG line 101 should be/users/:user_id.
> > HTTP code of 418 needs to be added
> > Full examples JSON payloads of each endpoint
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub, or mute the thread.
> >
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/autlamps/delay-backend-apidocs/pull/1#issuecomment-323513045>,
> or mute the thread
> .
>
-- 
Regards, Dharyin

**Comment by haydenwoodhead** [comment]
Added specific id names for endpoints. Also added http status code 418. Haven't added full examples as this is a large job, I'm going to need some help.

**Review by dominicbporter — APPROVED** [review]

**Pull request merged**
